name: image_utilities_example
description: Demonstrates how to use the image_utilities plugin.

publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+1
  image_utilities:
    path: ../
  path_provider: ^2.0.14
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
