name: image_utilities
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/sytex/image_utilities

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.siteplan.image_utilities
        pluginClass: ImageUtilitiesPlugin
      ios:
        pluginClass: ImageUtilitiesPlugin
